### PR TITLE
Update docker and docker-compose completions

### PR DESCRIPTION
**Pull request by mdemierre**
Update to latest releases:

- docker-completions updated for v1.11.1
- docker-compose-completions updated for v1.7.0

### CODE REVIEW

**Comment by bfontaine** [comment]
Thanks! Do you mind making two commits; one per formula? Each commit should be written as “`<formula> <version>`”, e.g. `docker-completions 1.11.0`.

**Comment by mdemierre** [comment]
No problem, I updated the branch to have two separate commits with the desired names. I also directly updated to docker 1.11.1 since it was released in the meantime.

**Comment by fox91** [comment]
+1

PS: @mdemierre now there's the version `1.7.1` of `docker-compose`.

**Comment by bfontaine** [comment]
@mdemierre Mind updating to 1.7.1? I’ll wait for you to merge.

**Comment by mdemierre** [comment]
Done 😄

**Comment by bfontaine** [comment]
Thanks a lot @mdemierre! 🎉

**Pull request closed without merging**
