### PR TITLE
launchctl-completion 1.0 (new formula)

### PR DESCRIPTION
**Pull request by CamJN**
Hard to believe this doesn't exist yet

### CODE REVIEW

**Comment by CamJN** [comment]
Ok, so my repo has to be popular in order to contribute? Really?

**Comment by bfontaine** [comment]
@CamJN This is the standard `brew audit` that applies to the core formulae; we’re less strict here 😃 

Seems like the checksum doesn’t match:
```
==> Fetching launchctl-completion from homebrew/completions
==> Downloading https://github.com/CamJN/launchctl-completion/archive/v1.0.tar.gz
==> Downloading from https://codeload.github.com/CamJN/launchctl-completion/tar.gz/v1.0
Downloaded to: /Library/Caches/Homebrew/launchctl-completion-1.0.tar.gz
SHA256: b21c39031fa41576d695720b295dce57358c320964f25d19a427798d0f0df7a0
==> Retrying download
==> Downloading https://github.com/CamJN/launchctl-completion/archive/v1.0.tar.gz
==> Downloading from https://codeload.github.com/CamJN/launchctl-completion/tar.gz/v1.0
Warning: Formula reports different SHA256: 272bb59b8186290a223cd0825a2cc60e99f2a43fa1e9875d2d48d7e8cf114a81
Downloaded to: /Library/Caches/Homebrew/launchctl-completion-1.0.tar.gz
SHA256: b21c39031fa41576d695720b295dce57358c320964f25d19a427798d0f0df7a0
```

**Comment by bfontaine** [comment]
Install fails:

```
==> Installing launchctl-completion from homebrew/completions
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160530-23747-20bme.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/build.rb /usr/local/Library/Taps/homebrew/homebrew-completions/launchctl-completion.rb --verbose
==> Downloading https://github.com/CamJN/launchctl-completion/archive/v1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/launchctl-completion-1.0.tar.gz
==> Verifying launchctl-completion-1.0.tar.gz checksum
tar xvzf /Library/Caches/Homebrew/launchctl-completion-1.0.tar.gz
x launchctl-completion-1.0/
x launchctl-completion-1.0/launchctl-completion.sh
Error: No such file or directory - launchctl-completion.bash
```

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
Merged; thank you @CamJN! 🎉

**Pull request closed without merging**
