### PR TITLE
brew-cask-completion: v2.0, fish support

### PR DESCRIPTION
**Pull request by xyb**
But homebrew's fish completion supporting is broken, so fish completion doesn't work.

### CODE REVIEW

**Comment by bfontaine** [comment]
> But homebrew's fish completion supporting is broken

What do you mean?

**Comment by xyb** [comment]
@bfontaine `fish_completion.install` could install script successfully, but the completion function doesn't work. I think brew installed script into `/usr/local/share/fish/vendor_completions.d/` but fish only using `/usr/share/fish/vendor-completions.d`, and `pkg-config --variable completionsdir fish` which is `/usr/local/Cellar/fish/2.2.0/share/fish/vendor_completions.d`, both of two directories not exist to cause homebrew's fish completion supporting broken.

**Comment by bfontaine** [comment]
@xyb Would you mind opening an issue about that on [Homebrew](https://github.com/Homebrew/homebrew/issues/new)?

**Comment by xyb** [comment]
@bfontaine Homebrew/homebrew#45124 opened already

**Comment by bfontaine** [comment]
Thanks!

**Comment by bfontaine** [comment]
Merged; thank you for your contribution @xyb! :tada:

**Pull request closed without merging**
