### PR TITLE
Update docker completion to v1.9.0

### PR DESCRIPTION
**Pull request by tonglil**

### CODE REVIEW

**Comment by bfontaine** [comment]
The test is failing:
```
==> source /usr/local/Cellar/docker-completion/1.9.0/etc/bash_completion.d/docker && complete -p docker
/usr/local/Cellar/docker-completion/1.9.0/etc/bash_completion.d/docker: line 731: syntax error near unexpected token `('
/usr/local/Cellar/docker-completion/1.9.0/etc/bash_completion.d/docker: line 731: `		*dm.@(blkdiscard|override_udev_sync_check|use_deferred_@(removal|deletion))=*)'
```

If this is due to Bash-only code you can try to wrap the whole command in `bash -c '...'`, see [`docker-machine-completion.rb`](https://github.com/Homebrew/homebrew-completions/blob/9fb2be4a5c2711a005a114ae3aaea66504193201/docker-machine-completion.rb#L17) for example.

**Comment by tonglil** [comment]
@bfontaine, I can do that. What about the other [completions](https://github.com/tonglil/homebrew-completions/blob/docker-completion-1.9.0/docker-completion.rb#L14)?

**Comment by bfontaine** [comment]
@tonglil If you have an idea on how to test these that’d be awesome; if not you can test the Bash completion only.

**Comment by bfontaine** [comment]
The test is still failing; there’s a bug in upstream’s completion script: https://github.com/docker/docker/commit/fb6ef9086d4f68a239a237dcdfeb6a4518163e28#commitcomment-14287645

**Comment by bfontaine** [comment]
This patch might work: https://github.com/albers/docker/commit/211e3b0df67d17989c7aff63d1a0098ad61f07a3.patch

**Comment by bfontaine** [comment]
Would you mind bumping this to 1.9.1? The upstream issue was fixed in this release.

**Comment by tonglil** [comment]
Yes, I'll fix it upon returning from vacation in a few days!

**Comment by bfontaine** [comment]
Thank you for your contribution to Homebrew, @tonglil; we appreciate it! :smile:

**Pull request closed without merging**
